deployment:
  tasks:
    - echo "Running build..."
    - cd tumul_sir
    - export VITE_API_BASE=https://astro-profile-1052447119554.europe-west1.run.app
    - npm install
    - npm run build
    - echo "Copying build to public_html..."
    - rm -rf /home/corpa2nz/public_html/*
    - cp -r dist/* /home/corpa2nz/public_html/